- name: Install prerequsites packages
  package:
    name: expect
    state: present

- name: Install MariaDB server
  package:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Secure MariaDB Installation
  script: mysql_secure.sh '{{ mysql_root_password }}' '{{ mysql_root_password }}'

- name: Configure DB and Admin User
  shell: mysql -u root -e "CREATE SCHEMA ospos;CREATE USER 'admin'@'%' IDENTIFIED BY '{{ mysql_admin_pass }}';GRANT ALL PRIVILEGES ON ospos . * TO 'admin'@'%' IDENTIFIED BY '{{ mysql_admin_pass }}' WITH GRANT OPTION;FLUSH PRIVILEGES;"
  ignore_errors: True

- name: Create tables
  shell: mysql -u admin -p{{ mysql_admin_pass }} -D ospos < /var/www/html/database/database.sql
  ignore_errors: True
